[build]
# Usa o Dockerfile na raiz
dockerfilePath = "Dockerfile"

[deploy]
# Número de réplicas
numReplicas = 1

# Desabilitar healthcheck temporariamente para ver logs de erro
# healthcheckPath = "/api/v1/health"
# healthcheckTimeout = 120

# Reinicia em caso de falha
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
